### ISSUE TITLE
V1.1.0 がα版になっている

### ISSUE THREAD

**Issue by riku22** [actlaboratory/DAC#26]
V1.1.0 ですが、α版になっている気がします。

1. [1.1.0 のリリースページ](https://github.com/actlaboratory/DAC/releases/tag/1.1.0) から `DAC-1.1.0.zip` をダウンロードする。
2. ダウンロードしたファイルを解凍し、 `DAC.exe` を実行する。
3. アップデート画面が表示されるので、1度キャンセルする。
4. 「ヘルプ」→「バージョン情報」で表示されているソフトウェアバージョンが `2212.31.0` となっている。

ご確認いただけますと幸いです。

**Comment by yamahubuki** [comment]
ご指摘ありがとうございます。
速やかに1.1.1へのバージョンアップを配信するとともに、本来アルファ版である2212.31.0および2212.31.783からのバージョンアップ確認は、サーバ側で1.1.0に読み替える処置をとります。

**Comment by yamahubuki** [comment]
v1.1.1を配信して解決しましたので、クローズさせていただきます。
ご報告ありがとうございました。
